#index:
 #  path: /
 #   controller: App\Controller\DefaultController::index
# config/routes.yaml
homepage:
    path: /
    controller: App\Controller\HomeController::index
dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

# ...